### ISSUE TITLE
You are a Monster

### ISSUE THREAD

**Issue by rspeed** [JesseBusman/falconheavy.space#1]
# Description

At some point in your life someone must have hurt you, and now you're taking it out on everyone else.

# Expected Behavior

Acting like a decent human being.

# Observed Behavior

You made this… *atrocity*, and felt fit to unleashed it on the world.

# Steps to Reproduce

Please don't.

**Comment by JesseBusman** [comment]
I was able to reproduce this. It's not a bug, it's a feature.

Your SSL certificate expired 8 days ago. _8 days ago!_ This is unacceptable. Millions of unsuspecting visitors are attempting to access your website, only to be met with giant error messages. Every three seconds a starving African child dies from a heart attack caused by these sudden bright red browser tabs about privacy errors and identity theft!

Tick, tock, dead. Tick, tock, dead. Tick, tock, dead.

I am contacting Unicef **right now**!

**Comment by rspeed** [comment]
Whoops!

**Comment by rspeed** [comment]
Hey, your website just gives a 404!

**Comment by rspeed** [comment]
https://jesbus.com/ PEOPLE ARE DYING!!!

**Comment by JesseBusman** [comment]
Fixed!

**Comment by rspeed** [comment]
Indeed. Closing the issue.
